### ISSUE TITLE
Production readiness ?

### ISSUE THREAD

**Issue by maximveksler** [kasei/kineo#18]
Hi, might be a bold move at this point but... have you heard of someone using it in a production environment ?

**Comment by kasei** [comment]
No. It's been mostly a side project of mine so far. Parts of Kineo started as a project to replace the Objective-C code in my app Porthole, but hasn't made it into production yet. Always happy to hear about people using my code, though!

**Comment by maximveksler** [comment]
Thank you for the information.

Please feel free to close the issue if preferred.
