### ISSUE TITLE
README build steps need update

### ISSUE THREAD

**Issue by cfilipov** [kasei/kineo#19]
Instructions on the README only say to run `swift build -c release` but first you need to `brew install serd`.

**Comment by kasei** [comment]
You're right, that's not included in the README. Did the `build` command tell you to install with `brew`?

**Comment by cfilipov** [comment]
It did not. I noticed that the Package.swift for swift-serd did have a `.systemLibrary` defined with a brew command (which I've never seen documented before, but spm in generally poorly documented) so I would assume that would at the very least prompt me to install if not do so itself. Perhaps my version of swift doesn't work that way:

```
$ swift --version
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.0.0
```

**Comment by kasei** [comment]
Strange. In the past I've had the package manager tell me that I needed to install via brew and/or apt.
